Add Metric Card
gitcoinco/gitcoin-ui pull request #100
Opened 2024-12-18 11:22 UTC by 0xKurt

fixes PAR-711

![image](https://github.com/user-attachments/assets/4d057a8b-cb67-4301-8710-e510924aba21)

![image](https://github.com/user-attachments/assets/2c554992-a9cd-4d2d-888c-17ffd655ab23)

2024-12-18 12:25 UTC, hussedev requested changes
Cool,

I like it, but what do you think if we create a Metric card with variants?

we could have props:

title, description, isAdded, onClick, onReadMore/onMore, and variant.

then depending on the variant we render a button or another, and an style or another.

2024-12-18 12:29 UTC, hussedev requested changes
left some comments

2024-12-18 12:29 UTC, hussedev commented on src/assets/icons/custom/index.ts
> +import Plus from "./plus.svg?react";
Hero icons have the solid 'plus' icon, so we wouldn't need the svg for it

2024-12-19 07:22 UTC, thelostone-mc approved these changes

2024-12-19 07:22 UTC, merged